import { useEffect,useMemo,useRef,useState } from 'react';
import { Activity,Archive,ArrowUp,AudioLines,BookOpen,BrainCircuit,ChevronDown,Code2,Database,FolderGit2,History,LockKeyhole,Mic,MoreHorizontal,Plus,Search,Settings2,ShieldCheck,Sparkles,Trash2,UserRound,Volume2,X } from 'lucide-react';
import { api,type Memory,type Message,type Preference } from './api';
import { useConversationControls, useConversationStatus } from '@elevenlabs/react';

type Page='Workspace'|'Personality'|'Memory'|'History'|'Privacy';
const nav=[['Workspace',AudioLines],['Personality',BrainCircuit],['Memory',FolderGit2],['History',History],['Privacy',ShieldCheck]] as const;
const demoStatus={mongo:false,openai:false,elevenlabs:false};

export default function App(){
 const [page,setPage]=useState<Page>('Workspace'),[prefs,setPrefs]=useState<Preference[]>([]),[memories,setMemories]=useState<Memory[]>([]),[messages,setMessages]=useState<Message[]>([]),[status,setStatus]=useState(demoStatus),[loading,setLoading]=useState(true);
 const refresh=async()=>{const [p,m,c,s]=await Promise.all([api.preferences(),api.memories(),api.messages(),api.status()]);setPrefs(p);setMemories(m);setMessages(c);setStatus(s);setLoading(false)};
 useEffect(()=>{refresh().catch(()=>setLoading(false))},[]);
 return <div className="shell"><Sidebar page={page} setPage={setPage}/><main><Topbar page={page} status={status}/>{loading?<div className="loader"><BrainCircuit size={34}/><span>Loading your coding personality…</span></div>:page==='Workspace'?<Workspace prefs={prefs} messages={messages} onMessage={m=>setMessages(x=>[...x,m])}/>:page==='Personality'?<Personality prefs={prefs} setPrefs={setPrefs}/>:page==='Memory'?<MemoryPage memories={memories} setMemories={setMemories}/>:page==='History'?<HistoryPage messages={messages}/>:<Privacy/>}</main></div>
}
function Sidebar({page,setPage}:{page:Page;setPage:(p:Page)=>void}){return <aside><div className="brand"><div className="mark"><Code2 size={19}/></div><div><b>DevPersona</b><small>Adaptive coding agent</small></div></div><nav>{nav.map(([n,I])=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><I size={18}/>{n}{n==='Personality'&&<span className="dot"/>}</button>)}</nav><div className="project"><small>CURRENT PROJECT</small><div className="project-card"><div className="project-icon">O</div><div><b>Orbit Mobile</b><span>Expo · TypeScript</span></div><ChevronDown size={15}/></div></div><div className="aside-bottom"><div className="learning"><Sparkles size={16}/><div><b>Learning is on</b><span>12 signals this week</span></div></div><div className="profile"><div className="avatar">AR</div><div><b>Aaron Ramirez</b><span>Personal workspace</span></div><MoreHorizontal size={18}/></div></div></aside>}
function Topbar({page,status}:{page:Page;status:typeof demoStatus}){return <header><div><h1>{page==='Workspace'?'Voice workspace':page==='Personality'?'Developer personality':page==='Memory'?'Project memory':page==='History'?'Conversation history':'Privacy & data'}</h1><p>{page==='Workspace'?'Talk through code. DevPersona adapts as you work.':page==='Personality'?'The preferences that shape every response.':page==='Memory'?'Decisions and context remembered for Orbit Mobile.':page==='History'?'Review what you built and what DevPersona learned.':'Control what is learned, retained, and shared.'}</p></div><div className="top-actions"><div className="status"><span className={status.mongo?'online':'demo'}/>{status.mongo?'Atlas connected':'Demo mode'}</div><button className="icon-btn"><Search size={18}/></button><button className="icon-btn"><Settings2 size={18}/></button></div></header>}
function Workspace({prefs,messages,onMessage}:{prefs:Preference[];messages:Message[];onMessage:(m:Message)=>void}){
 const [text,setText]=useState(''),[instructions,setInstructions]=useState(''),[busy,setBusy]=useState(false),[demoListening,setDemoListening]=useState(false); const end=useRef<HTMLDivElement>(null); const {startSession,endSession}=useConversationControls(); const {status:voiceStatus}=useConversationStatus(); const listening=voiceStatus==='connected'||demoListening;
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,busy]);
 const send=async()=>{if(!text.trim()||busy)return;const prompt=text.trim();const u={id:crypto.randomUUID(),role:'user' as const,content:prompt,createdAt:new Date().toISOString()};onMessage(u);setText('');setBusy(true);try{const r=await api.chat(prompt,instructions);onMessage(r.message)}catch{onMessage({id:crypto.randomUUID(),role:'assistant',content:'I hit a connection problem. Your message is still here—start the API and try again.',createdAt:new Date().toISOString()})}finally{setBusy(false)}};
 const toggleVoice=async()=>{if(voiceStatus==='connected'){await endSession();return}if(demoListening){setDemoListening(false);return}const session=await fetch('/api/voice/session').then(r=>r.json());if(session.agentId){await navigator.mediaDevices.getUserMedia({audio:true});await startSession({agentId:session.agentId})}else setDemoListening(true)};
 return <div className="workspace"><section className="chat"><div className="context-strip"><Sparkles size={15}/><span><b>Personality active</b> · {prefs.length} preferences applied</span><button onClick={()=>{}}>View reasoning</button></div><div className="messages">{messages.map(m=><div className={'message '+m.role} key={m.id}>{m.role==='assistant'&&<div className="ai-avatar"><Code2 size={16}/></div>}<div><small>{m.role==='assistant'?'DEVPERSONA':'YOU'}</small><div className="bubble">{m.content}</div>{m.preferences?.length?<span className="used"><BrainCircuit size={12}/> Used {m.preferences.length} personality signals</span>:null}</div></div>)}{busy&&<div className="message assistant"><div className="ai-avatar"><Code2 size={16}/></div><div className="typing"><i/><i/><i/></div></div>}<div ref={end}/></div><div className="composer"><div className="instruction"><LockKeyhole size={13}/><input value={instructions} onChange={e=>setInstructions(e.target.value)} placeholder="Current instruction (highest priority), e.g. no refactoring"/></div><textarea value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}}} placeholder="Ask DevPersona to build, debug, or explain…"/><div className="compose-row"><button className={'voice '+(listening?'live':'')} onClick={toggleVoice}><Mic size={18}/>{listening?'End conversation':'Talk to DevPersona'}</button><div><span>⌘ ↵ to send</span><button className="send" onClick={send}><ArrowUp size={18}/></button></div></div></div></section><RightPanel prefs={prefs} listening={listening}/></div>}
function RightPanel({prefs,listening}:{prefs:Preference[];listening:boolean}){return <section className="right-panel"><div className={'voice-orb '+(listening?'listening':'')}><div className="orb-core"><AudioLines size={30}/></div><span/><span/><span/></div><h3>{listening?'I’m listening':'Voice ready'}</h3><p>{listening?'Say what you want to build.':'Press the mic or use the composer.'}</p><button className="outline"><Volume2 size={16}/> Avery · Conversational</button><div className="panel-rule"/><div className="panel-title"><span>Active personality</span><button><MoreHorizontal size={17}/></button></div>{prefs.slice(0,5).map(p=><div className="signal" key={p.id}><div><small>{p.label}</small><b>{p.value}</b></div><span>{Math.round(p.confidence*100)}%</span></div>)}<div className="precedence"><small>RESPONSE PRECEDENCE</small><div><b>1</b> Current instruction</div><div><b>2</b> Project preferences</div><div><b>3</b> Global personality</div></div></section>}
function Personality({prefs,setPrefs}:{prefs:Preference[];setPrefs:(p:Preference[])=>void}){const [filter,setFilter]=useState<'all'|'global'|'project'>('all'),[adding,setAdding]=useState(false);const shown=prefs.filter(p=>filter==='all'||p.scope===filter);const avg=Math.round(prefs.reduce((a,p)=>a+p.confidence,0)/Math.max(1,prefs.length)*100);return <div className="page personality"><div className="stat-grid"><Stat icon={BrainCircuit} value={`${avg}%`} label="Personality confidence" note="+4% this month"/><Stat icon={Activity} value={String(prefs.length)} label="Active preferences" note="3 recently updated"/><Stat icon={FolderGit2} value="4" label="Known projects" note="Orbit is active"/><Stat icon={Sparkles} value="128" label="Signals learned" note="Across 31 sessions"/></div><div className="section-head"><div><h2>Your coding DNA</h2><p>Edit anything. Explicit choices always beat inferred preferences.</p></div><button className="primary" onClick={()=>setAdding(true)}><Plus size={17}/> Add preference</button></div><div className="tabs">{(['all','global','project'] as const).map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div><div className="pref-list">{shown.map(p=><div className="pref-card" key={p.id}><div className="pref-icon">{p.category==='Stack'?<Code2/>:p.category==='State'?<Database/>:p.category==='Responses'?<BookOpen/>:<BrainCircuit/>}</div><div className="pref-main"><div><small>{p.category} · {p.label}</small><h3>{p.value}</h3></div><div className="scope"><span className={p.scope}>{p.scope}</span><span className={'source '+p.source}>{p.source}</span></div><p>“{p.evidence.replace(/[“”]/g,'')}”</p></div><div className="confidence"><b>{Math.round(p.confidence*100)}%</b><span>confidence</span><div><i style={{width:`${p.confidence*100}%`}}/></div></div><button className="delete" onClick={async()=>{await api.deletePreference(p.id);setPrefs(prefs.filter(x=>x.id!==p.id))}}><Trash2 size={16}/></button></div>)}</div>{adding&&<AddPreference close={()=>setAdding(false)} add={p=>setPrefs([p,...prefs])}/>}</div>}
function Stat({icon:I,value,label,note}:{icon:any;value:string;label:string;note:string}){return <div className="stat"><I size={20}/><b>{value}</b><span>{label}</span><small>{note}</small></div>}
function AddPreference({close,add}:{close:()=>void;add:(p:Preference)=>void}){const [value,setValue]=useState(''),[evidence,setEvidence]=useState('');const save=async()=>{if(!value)return;add(await api.addPreference({category:'Custom',label:'Explicit preference',value,confidence:1,scope:'global',source:'explicit',evidence:evidence||'Added manually in preference controls.'}));close()};return <div className="modal-bg"><div className="modal"><button className="close" onClick={close}><X/></button><div className="modal-icon"><Sparkles/></div><h2>Add a preference</h2><p>Manual preferences start at 100% confidence.</p><label>What should DevPersona know?<input autoFocus value={value} onChange={e=>setValue(e.target.value)} placeholder="e.g. Prefer named exports"/></label><label>Supporting evidence<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} placeholder="Why or when should this apply?"/></label><button className="primary full" onClick={save}>Save preference</button></div></div>}
function MemoryPage({memories,setMemories}:{memories:Memory[];setMemories:(m:Memory[])=>void}){const [text,setText]=useState('');const add=async()=>{if(!text)return;const m=await api.addMemory(text,'decision');setMemories([m,...memories]);setText('')};return <div className="page"><div className="memory-hero"><div><span className="eyebrow">ORBIT MOBILE</span><h2>A shared brain for your project.</h2><p>Decisions, constraints, and patterns are embedded and retrieved before every answer.</p></div><div className="memory-count"><Database/><b>{memories.length}</b><span>memories indexed</span></div></div><div className="add-memory"><input value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>e.key==='Enter'&&add()} placeholder="Add a decision, constraint, or project convention…"/><button className="primary" onClick={add}><Plus size={17}/> Remember</button></div><div className="memory-grid">{memories.map(m=><article key={m.id}><div className="memory-top"><span>{m.kind}</span><MoreHorizontal/></div><p>{m.text}</p><small>Stored in Atlas · Retrieved semantically</small></article>)}</div></div>}
function HistoryPage({messages}:{messages:Message[]}){const groups=useMemo(()=>messages.reduce((a,m,i)=>{if(m.role==='user')a.push({title:m.content,reply:messages[i+1]?.role==='assistant'?messages[i+1].content:''});return a},[] as {title:string;reply:string}[]),[messages]);return <div className="page"><div className="history-search"><Search/><input placeholder="Search conversations, code, and decisions…"/></div><div className="section-head"><div><h2>Recent conversations</h2><p>Your working history, searchable and private.</p></div><button className="outline"><Archive size={16}/> Archive</button></div><div className="history-list">{groups.map((g,i)=><article><div className="history-icon"><Code2/></div><div><small>ORBIT MOBILE · {i===0?'TODAY':'RECENTLY'}</small><h3>{g.title}</h3><p>{g.reply}</p><span><BrainCircuit size={13}/> Personality applied</span></div><MoreHorizontal/></article>)}</div></div>}
function Privacy(){const [learning,setLearning]=useState(true),[voice,setVoice]=useState(false),[retention,setRetention]=useState('Forever');return <div className="page"><div className="privacy-banner"><ShieldCheck/><div><h2>Your code stays yours.</h2><p>DevPersona only learns what you allow. Manage collection and retention at any time.</p></div></div><div className="settings-card"><h3>Learning & personalization</h3><Setting title="Learn from conversations" text="Extract coding preferences from what you say and write." on={learning} toggle={()=>setLearning(!learning)}/><Setting title="Store voice recordings" text="Off by default. Transcripts can still be retained as conversation history." on={voice} toggle={()=>setVoice(!voice)}/><div className="setting"><div><b>Conversation retention</b><p>Choose how long encrypted transcripts remain available.</p></div><select value={retention} onChange={e=>setRetention(e.target.value)}><option>30 days</option><option>1 year</option><option>Forever</option></select></div></div><div className="settings-card"><h3>Data controls</h3><button className="data-action"><Database/><div><b>Export my data</b><span>Preferences, memories, and conversations</span></div><ArrowUp/></button><button className="data-action danger"><Trash2/><div><b>Delete all learned data</b><span>Permanently remove your personality and project memory</span></div><ArrowUp/></button></div></div>}
function Setting({title,text,on,toggle}:{title:string;text:string;on:boolean;toggle:()=>void}){return <div className="setting"><div><b>{title}</b><p>{text}</p></div><button className={'toggle '+(on?'on':'')} onClick={toggle}><i/></button></div>}
